
version: '3.8'



services:


  db:
    ports:
      - "5432:5432"
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: postgreSQL
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql@16/data

    restart: always

  backend:
    build: .
    container_name: test_cons
    ports:
      - "8081:8081"
    environment:
      db-url: jdbc:postgresql://db:5432/postgres
      db-username: postgres
      db-password: postgres
    depends_on:
      - db
    restart: always
