version: '3.8'

services:
  app:
    image: openjdk:17-jdk-slim
    container_name: task_management_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    volumes:
      - ./target/task_management_app.jar:/app/task_management_app.jar
    entrypoint: ["java", "-jar", "/app/task_management_app.jar"]

  db:
    image: postgres:13
    container_name: task_management_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: