
version: '3.8'

services:
  api:
    image: openjdk:19
    ports:
      - "8081:8081"
    volumes:
      - C:/Users/kamal/IdeaProjects/test-effective-mobile/out/artifacts/test_effective_mobile_jar:/app
      - C:/Users/kamal/IdeaProjects/test-effective-mobile/src:/app/src
    command: ["java", "-jar", "/app/test-effective-mobile.jar"]
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - SPRING_APPLICATION_JSON=application.properties
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: localhost:5432
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge